version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    image: auth-app
    container_name: auth-app
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - 8090:8090
    command: uvicorn src.main:app --host 0.0.0.0 --port 8090 --reload

  postgres:
      image: postgres:latest
      container_name: postgres-auth-app
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      env_file:
        - .env
      ports:
        - 5432:5432
    
